/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Corte1;

import java.io.File;
import java.io.FileInputStream;
import java.util.ArrayList;
import java.util.Properties;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author sebastian
 */
public class Principal extends javax.swing.JFrame {

    private ArrayList<Empleado> empleados = new ArrayList<Empleado>();
    private ArrayList<Equipo> equipos = new ArrayList<Equipo>();
    private ArrayList<Usuario> usuarios = new ArrayList<Usuario>();
    private ArrayList<Solicitud> solicitudes = new ArrayList<Solicitud>();
    private ArrayList<TipoSolicitud> tiposSolicitudes=new ArrayList<TipoSolicitud>();
    private ArrayList<Area> areas=new ArrayList<Area>();
    private Solicitud solicitud;
    private int cantSolicitudes=0;
    public Principal() {
        try {
            cargarEmpleados();
            cargarEquipos();
            cargarUsuarios();
            cargarAreas();
            cargarTiposSolicitudes();
            asociarEmpleadosArea();
            asociarEquiposUsuarios();
        } catch (Exception e) {
            e.printStackTrace();
        }
        initComponents();
        PanelEquipo.setVisible(false);
        PanelEmpleado.setVisible(false);
        PanelSolicitud.setVisible(false);
        PanelArea.setVisible(true);
        PanelTipoSolicitud.setVisible(false);
        PanelUsuario.setVisible(false);
        lstAreas.setListData(areas.toArray());
//        this.cmbUsuarioEquipo.addItem("seleccione un usuario para el equipo");
        for (Usuario usuario : usuarios) {
            cmbUsuarioEquipo.addItem(usuario);
        }
//        this.cmbTipos.addItem("seleccione");
        for (TipoSolicitud tipoSolicitud : tiposSolicitudes) {
            cmbTipos.addItem(tipoSolicitud);
        }
//        this.cmbTipo.addItem("Seleccione Tipo De Solicitud");
        for (TipoSolicitud tipoSolicitud : tiposSolicitudes) {
            cmbTipo.addItem(tipoSolicitud);
        }
//        this.cmbArea.addItem("Seleccione Area ");
        for (Area area : areas) {
            cmbArea.addItem(area);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelTitulo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PanelMenu = new javax.swing.JPanel();
        btnEquipo = new javax.swing.JButton();
        btnUsuario = new javax.swing.JButton();
        btnSolicitud = new javax.swing.JButton();
        btnArea = new javax.swing.JButton();
        btnEmpleado = new javax.swing.JButton();
        btnTipoSolicitud = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        PanelEquipo = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstEquipos = new javax.swing.JList();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNombreEquipo = new javax.swing.JTextField();
        txtIdEquipo = new javax.swing.JTextField();
        btnAddEquipo = new javax.swing.JButton();
        cmbUsuarioEquipo = new javax.swing.JComboBox();
        PanelUsuario = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        lstUsuariosEx = new javax.swing.JList();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtNombreUsuario = new javax.swing.JTextField();
        txtIdUsuario = new javax.swing.JTextField();
        btnAgregarUsuario = new javax.swing.JButton();
        PanelSolicitud = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstUsuarios = new javax.swing.JList();
        cmbTipos = new javax.swing.JComboBox();
        btnAgregarSolicitud = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstSlicitudes = new javax.swing.JList();
        PanelArea = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        lstAreas = new javax.swing.JList();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtNombreArea = new javax.swing.JTextField();
        txtIdArea = new javax.swing.JTextField();
        btnAddArea = new javax.swing.JButton();
        PanelEmpleado = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        lstEmpleados = new javax.swing.JList();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        cmbTipo = new javax.swing.JComboBox();
        txtNombreEmpleado = new javax.swing.JTextField();
        txtIdEmpleado = new javax.swing.JTextField();
        cmbArea = new javax.swing.JComboBox();
        btnAddEmpleado = new javax.swing.JButton();
        PanelTipoSolicitud = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        lstTipos = new javax.swing.JList();
        jLabel18 = new javax.swing.JLabel();
        txtNobreTipo = new javax.swing.JTextField();
        btnAgregarTipoSolicitud = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelTitulo.setBackground(new java.awt.Color(0, 102, 255));

        jLabel1.setFont(new java.awt.Font("Snap ITC", 0, 18)); // NOI18N
        jLabel1.setText("Help Desk");

        javax.swing.GroupLayout PanelTituloLayout = new javax.swing.GroupLayout(PanelTitulo);
        PanelTitulo.setLayout(PanelTituloLayout);
        PanelTituloLayout.setHorizontalGroup(
            PanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTituloLayout.createSequentialGroup()
                .addContainerGap(304, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(241, 241, 241))
        );
        PanelTituloLayout.setVerticalGroup(
            PanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTituloLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        getContentPane().add(PanelTitulo, java.awt.BorderLayout.PAGE_START);

        PanelMenu.setBackground(new java.awt.Color(51, 204, 255));

        btnEquipo.setText("Equipo");
        btnEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEquipoActionPerformed(evt);
            }
        });

        btnUsuario.setText("Usuario");
        btnUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuarioActionPerformed(evt);
            }
        });

        btnSolicitud.setText("Solicitud");
        btnSolicitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSolicitudActionPerformed(evt);
            }
        });

        btnArea.setText("Area");
        btnArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAreaActionPerformed(evt);
            }
        });

        btnEmpleado.setText("Empleado");
        btnEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpleadoActionPerformed(evt);
            }
        });

        btnTipoSolicitud.setText("Tipo solicitud");
        btnTipoSolicitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTipoSolicitudActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelMenuLayout = new javax.swing.GroupLayout(PanelMenu);
        PanelMenu.setLayout(PanelMenuLayout);
        PanelMenuLayout.setHorizontalGroup(
            PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEmpleado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                    .addComponent(btnArea, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSolicitud, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEquipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(PanelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnTipoSolicitud)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelMenuLayout.setVerticalGroup(
            PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMenuLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(btnEquipo)
                .addGap(18, 18, 18)
                .addComponent(btnUsuario)
                .addGap(18, 18, 18)
                .addComponent(btnSolicitud)
                .addGap(18, 18, 18)
                .addComponent(btnArea)
                .addGap(18, 18, 18)
                .addComponent(btnEmpleado)
                .addGap(18, 18, 18)
                .addComponent(btnTipoSolicitud)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        getContentPane().add(PanelMenu, java.awt.BorderLayout.LINE_START);

        PanelEquipo.setBackground(new java.awt.Color(255, 102, 0));

        jLabel5.setText("Equipos Existentes");

        jScrollPane3.setViewportView(lstEquipos);

        jLabel6.setText("ID:");

        jLabel7.setText("Nombre:");

        btnAddEquipo.setText("Agregar Equipo");
        btnAddEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddEquipoActionPerformed(evt);
            }
        });

        cmbUsuarioEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbUsuarioEquipoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelEquipoLayout = new javax.swing.GroupLayout(PanelEquipo);
        PanelEquipo.setLayout(PanelEquipoLayout);
        PanelEquipoLayout.setHorizontalGroup(
            PanelEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEquipoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(98, 98, 98))
            .addGroup(PanelEquipoLayout.createSequentialGroup()
                .addGroup(PanelEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelEquipoLayout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(btnAddEquipo))
                    .addGroup(PanelEquipoLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(PanelEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbUsuarioEquipo, 0, 164, Short.MAX_VALUE)
                            .addComponent(txtNombreEquipo)
                            .addComponent(txtIdEquipo, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );
        PanelEquipoLayout.setVerticalGroup(
            PanelEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEquipoLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel5)
                .addGroup(PanelEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PanelEquipoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelEquipoLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(PanelEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(txtIdEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PanelEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtNombreEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(cmbUsuarioEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAddEquipo)))
                .addContainerGap(106, Short.MAX_VALUE))
        );

        PanelUsuario.setBackground(new java.awt.Color(204, 204, 0));

        jLabel8.setText("Usuarios Existentes");

        jScrollPane4.setViewportView(lstUsuariosEx);

        jLabel9.setText("ID:");

        jLabel10.setText("Nombre:");

        btnAgregarUsuario.setText("Agregar Usuario");
        btnAgregarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelUsuarioLayout = new javax.swing.GroupLayout(PanelUsuario);
        PanelUsuario.setLayout(PanelUsuarioLayout);
        PanelUsuarioLayout.setHorizontalGroup(
            PanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelUsuarioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(96, 96, 96))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelUsuarioLayout.createSequentialGroup()
                .addGroup(PanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelUsuarioLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(PanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(PanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombreUsuario)
                            .addComponent(txtIdUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)))
                    .addGroup(PanelUsuarioLayout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(btnAgregarUsuario)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );
        PanelUsuarioLayout.setVerticalGroup(
            PanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelUsuarioLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel8)
                .addGroup(PanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelUsuarioLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelUsuarioLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(PanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtIdUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(PanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59)
                        .addComponent(btnAgregarUsuario)))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        PanelSolicitud.setBackground(new java.awt.Color(102, 255, 0));

        jLabel2.setText("Seleccione Usuario");

        jLabel3.setText("Seleccione Tipo De Solicitud");

        jScrollPane1.setViewportView(lstUsuarios);

        btnAgregarSolicitud.setText("Agregar Solicitud");
        btnAgregarSolicitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarSolicitudActionPerformed(evt);
            }
        });

        jLabel4.setText("Descripcion");

        jScrollPane2.setViewportView(lstSlicitudes);

        javax.swing.GroupLayout PanelSolicitudLayout = new javax.swing.GroupLayout(PanelSolicitud);
        PanelSolicitud.setLayout(PanelSolicitudLayout);
        PanelSolicitudLayout.setHorizontalGroup(
            PanelSolicitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSolicitudLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(PanelSolicitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelSolicitudLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(56, 56, 56))
                    .addGroup(PanelSolicitudLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)))
                .addGroup(PanelSolicitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cmbTipos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAgregarSolicitud, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelSolicitudLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(147, 147, 147))
        );
        PanelSolicitudLayout.setVerticalGroup(
            PanelSolicitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSolicitudLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(PanelSolicitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGroup(PanelSolicitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelSolicitudLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(PanelSolicitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addGap(29, 29, 29)
                        .addGroup(PanelSolicitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanelSolicitudLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(cmbTipos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(btnAgregarSolicitud))))
        );

        PanelArea.setBackground(new java.awt.Color(255, 0, 51));

        jLabel11.setText("Areas Existentes");

        jScrollPane5.setViewportView(lstAreas);

        jLabel12.setText("ID:");

        jLabel13.setText("Nombre:");

        btnAddArea.setText("Agregar Area");
        btnAddArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAreaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelAreaLayout = new javax.swing.GroupLayout(PanelArea);
        PanelArea.setLayout(PanelAreaLayout);
        PanelAreaLayout.setHorizontalGroup(
            PanelAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAreaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(90, 90, 90))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAreaLayout.createSequentialGroup()
                .addGroup(PanelAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelAreaLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(PanelAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(PanelAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombreArea)
                            .addComponent(txtIdArea, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAreaLayout.createSequentialGroup()
                        .addContainerGap(138, Short.MAX_VALUE)
                        .addComponent(btnAddArea)
                        .addGap(115, 115, 115)))
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        PanelAreaLayout.setVerticalGroup(
            PanelAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAreaLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel11)
                .addGroup(PanelAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelAreaLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelAreaLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(PanelAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtIdArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(PanelAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txtNombreArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(70, 70, 70)
                        .addComponent(btnAddArea)))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        PanelEmpleado.setBackground(new java.awt.Color(153, 153, 153));

        jScrollPane6.setViewportView(lstEmpleados);

        jLabel14.setText("Empleados Existentes");

        jLabel15.setText("ID:");

        jLabel16.setText("Nombre:");

        btnAddEmpleado.setText("Agregar Empleado");
        btnAddEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddEmpleadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelEmpleadoLayout = new javax.swing.GroupLayout(PanelEmpleado);
        PanelEmpleado.setLayout(PanelEmpleadoLayout);
        PanelEmpleadoLayout.setHorizontalGroup(
            PanelEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEmpleadoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(72, 72, 72))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelEmpleadoLayout.createSequentialGroup()
                .addGroup(PanelEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelEmpleadoLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(PanelEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel15))
                        .addGap(18, 18, 18)
                        .addGroup(PanelEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbArea, 0, 211, Short.MAX_VALUE)
                            .addComponent(cmbTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNombreEmpleado)
                            .addComponent(txtIdEmpleado)))
                    .addGroup(PanelEmpleadoLayout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(btnAddEmpleado)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        PanelEmpleadoLayout.setVerticalGroup(
            PanelEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEmpleadoLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel14)
                .addGroup(PanelEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelEmpleadoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelEmpleadoLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(PanelEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(txtIdEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(PanelEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(txtNombreEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cmbArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(btnAddEmpleado)))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        PanelTipoSolicitud.setBackground(new java.awt.Color(153, 153, 0));

        jLabel17.setText("Nombre:");

        jScrollPane7.setViewportView(lstTipos);

        jLabel18.setText("Tipos de solicitudes existentes");

        btnAgregarTipoSolicitud.setText("Agregar Tipo De Solicitud");
        btnAgregarTipoSolicitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarTipoSolicitudActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelTipoSolicitudLayout = new javax.swing.GroupLayout(PanelTipoSolicitud);
        PanelTipoSolicitud.setLayout(PanelTipoSolicitudLayout);
        PanelTipoSolicitudLayout.setHorizontalGroup(
            PanelTipoSolicitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTipoSolicitudLayout.createSequentialGroup()
                .addGroup(PanelTipoSolicitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelTipoSolicitudLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNobreTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTipoSolicitudLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAgregarTipoSolicitud)
                        .addGap(83, 83, 83)))
                .addGroup(PanelTipoSolicitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );
        PanelTipoSolicitudLayout.setVerticalGroup(
            PanelTipoSolicitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTipoSolicitudLayout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addGroup(PanelTipoSolicitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtNobreTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82)
                .addComponent(btnAgregarTipoSolicitud)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTipoSolicitudLayout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelEquipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PanelSolicitud, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PanelUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PanelArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PanelEmpleado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PanelTipoSolicitud, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelEquipo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PanelSolicitud, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PanelUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PanelArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PanelEmpleado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PanelTipoSolicitud, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1.setLayer(PanelEquipo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(PanelUsuario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(PanelSolicitud, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(PanelArea, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(PanelEmpleado, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(PanelTipoSolicitud, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(jLayeredPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuarioActionPerformed
        PanelEquipo.setVisible(false);
        PanelEmpleado.setVisible(false);
        PanelSolicitud.setVisible(false);
        PanelArea.setVisible(false);
        PanelTipoSolicitud.setVisible(false);
        PanelUsuario.setVisible(true);
        lstUsuariosEx.setListData(usuarios.toArray());
    }//GEN-LAST:event_btnUsuarioActionPerformed

    private void btnEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEquipoActionPerformed
        PanelEquipo.setVisible(true);
        PanelEmpleado.setVisible(false);
        PanelSolicitud.setVisible(false);
        PanelArea.setVisible(false);
        PanelTipoSolicitud.setVisible(false);
        PanelUsuario.setVisible(false);
        lstEquipos.setListData(equipos.toArray());
    }//GEN-LAST:event_btnEquipoActionPerformed

    private void btnSolicitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolicitudActionPerformed
        PanelEquipo.setVisible(false);
        PanelEmpleado.setVisible(false);
        PanelSolicitud.setVisible(true);
        PanelArea.setVisible(false);
        PanelTipoSolicitud.setVisible(false);
        PanelUsuario.setVisible(false);
        lstUsuarios.setListData(usuarios.toArray());
        
    }//GEN-LAST:event_btnSolicitudActionPerformed

    private void btnAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAreaActionPerformed
        PanelEquipo.setVisible(false);
        PanelEmpleado.setVisible(false);
        PanelSolicitud.setVisible(false);
        PanelArea.setVisible(true);
        PanelTipoSolicitud.setVisible(false);
        PanelUsuario.setVisible(false);
        lstAreas.setListData(areas.toArray());
    }//GEN-LAST:event_btnAreaActionPerformed

    private void btnEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpleadoActionPerformed
       PanelEquipo.setVisible(false);
        PanelEmpleado.setVisible(true);
        PanelSolicitud.setVisible(false);
        PanelArea.setVisible(false);
        PanelTipoSolicitud.setVisible(false);
        PanelUsuario.setVisible(false);
        lstEmpleados.setListData(empleados.toArray());
    }//GEN-LAST:event_btnEmpleadoActionPerformed

    private void btnTipoSolicitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTipoSolicitudActionPerformed
        PanelEquipo.setVisible(false);
        PanelEmpleado.setVisible(false);
        PanelSolicitud.setVisible(false);
        PanelArea.setVisible(false);
        PanelTipoSolicitud.setVisible(true);
        PanelUsuario.setVisible(false);
        lstTipos.setListData(tiposSolicitudes.toArray());
    }//GEN-LAST:event_btnTipoSolicitudActionPerformed

    private void btnAgregarSolicitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarSolicitudActionPerformed
        if(lstUsuarios.isSelectionEmpty()){
           JOptionPane.showMessageDialog(this,"seleccione un usuario");
       }else{
            String strDescripcion = txtDescripcion.getText();
            if (strDescripcion.equals("")) {
                JOptionPane.showMessageDialog(this,"Descripcion es requerida");
            } else {
                solicitud = new Solicitud();
                Usuario usuario = (Usuario) lstUsuarios.getSelectedValue();
                solicitud.setId(cantSolicitudes++);
                solicitud.setDescripcion(strDescripcion);
                solicitud.setUsuario(usuario);
                TipoSolicitud tipo = (TipoSolicitud) cmbTipos.getSelectedItem();
                solicitud.setTipo(tipo);
                solicitudes.add(solicitud);
                 for (Empleado empleado : empleados) {
                     if(empleado.getTipoSolicitud().toString().equals(solicitud.getTipo().toString())){
                         solicitud.setIdEmpleado(empleado.getId());

                     }
                 }
                 for (Area area : areas) {
//                     System.out.println(area.getNombre());
//                     System.out.println(solicitud.getTipo().getNombre());
                     if(area.getNombre().toString().equals(solicitud.getTipo().getNombre())){
                         solicitud.setIdArea(area.getId());
                     }
                 }
                lstSlicitudes.setListData(solicitudes.toArray());
            }
           
       }
    }//GEN-LAST:event_btnAgregarSolicitudActionPerformed

    private void btnAddEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEquipoActionPerformed
        String strIdEquipo = txtIdEquipo.getText();
        String strNombreEquipo = txtNombreEquipo.getText();
        if (strIdEquipo.equals("") || strNombreEquipo.equals("")) {
            JOptionPane.showMessageDialog(this, "Id o nombre son requeridos");
        } else {
            try {
                Usuario usuario = (Usuario) cmbUsuarioEquipo.getSelectedItem();
                Equipo equipo = new Equipo();
                int idEquipo = 0 ;
                idEquipo = Integer.parseInt(strIdEquipo);
                equipo.setId(idEquipo);
                equipo.setNombre(strNombreEquipo);
                equipos.add(equipo);
                lstEquipos.setListData(equipos.toArray());
                usuario.agregarEquipo(equipo);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        
        }
    }//GEN-LAST:event_btnAddEquipoActionPerformed

    private void btnAgregarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarUsuarioActionPerformed
        String strIdUsuario = txtIdUsuario.getText();
        String strNombreUsuario = txtNombreUsuario.getText();
        if (strIdUsuario.equals("") || strNombreUsuario.equals("")) {
            JOptionPane.showMessageDialog(this, "Id o nombre son requeridos");
        }else{
            try {
                Usuario usuario =new Usuario();
                int idUsuario = 0;
                idUsuario = Integer.parseInt(strIdUsuario);
                usuario.setId(idUsuario);
                usuario.setNombre(strNombreUsuario);
                usuarios.add(usuario);
                lstUsuariosEx.setListData(usuarios.toArray());
                cmbUsuarioEquipo.setModel(new DefaultComboBoxModel(usuarios.toArray()));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
            
        }
    }//GEN-LAST:event_btnAgregarUsuarioActionPerformed

    private void btnAddAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAreaActionPerformed
        String strIdArea = txtIdArea.getText();
        String strNombreArea = txtNombreArea.getText();
        if (strIdArea.equals("") || strNombreArea.equals("")) {
            JOptionPane.showMessageDialog(this, "Id o nombre son requeridos");
        } else {
            try {
                Area area =new Area();
                int idArea = Integer.parseInt(strIdArea);
                area.setId(idArea);
                area.setNombre(strNombreArea);
                areas.add(area);
                lstAreas.setListData(areas.toArray());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
        
    }//GEN-LAST:event_btnAddAreaActionPerformed

    private void btnAddEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEmpleadoActionPerformed
        String strIdEmpleado = txtIdEmpleado.getText();
        String strNombreEmpleado = txtNombreEmpleado.getText();
        if (strIdEmpleado.equals("") || strNombreEmpleado.equals("")) {
            JOptionPane.showMessageDialog(this, "Id o nombre son requeridos");
        } else {
            try {
                Area area =(Area) cmbArea.getSelectedItem();
                TipoSolicitud tipoSolicitud =(TipoSolicitud) cmbTipo.getSelectedItem();
                Empleado empleado =new Empleado();
                int idEmpleado = Integer.parseInt(strIdEmpleado);
                empleado.setId(idEmpleado);
                empleado.setNombre(strNombreEmpleado);
                empleado.setTipoSolicitud(tipoSolicitud.getNombre());
                empleados.add(empleado);
                lstEmpleados.setListData(empleados.toArray());
                area.adicionarIdEmpleado(empleado);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
    }//GEN-LAST:event_btnAddEmpleadoActionPerformed

    private void btnAgregarTipoSolicitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarTipoSolicitudActionPerformed
        String strNombreTipo = txtNobreTipo.getText();
        if (strNombreTipo.equals("")) {
            JOptionPane.showMessageDialog(this, "Nombre es requerido");
        } else {
            TipoSolicitud tipoSolicitud =new TipoSolicitud();
            tipoSolicitud.setNombre(txtNobreTipo.getText());
            tiposSolicitudes.add(tipoSolicitud);
            lstTipos.setListData(tiposSolicitudes.toArray());
            cmbTipo.setModel(new DefaultComboBoxModel(tiposSolicitudes.toArray()));
            cmbTipos.setModel(new DefaultComboBoxModel(tiposSolicitudes.toArray()));
        }
    }//GEN-LAST:event_btnAgregarTipoSolicitudActionPerformed

    private void cmbUsuarioEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbUsuarioEquipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbUsuarioEquipoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    public void cargarTiposSolicitudes() throws Exception{
                File arch=new File("./data/tipos.properties");
		Properties props=new Properties();
		FileInputStream fis=new FileInputStream(arch);
		props.load(fis);
		String cantTiposSolicitudes = props.getProperty("cantidadTiposSolicitudes");
                int intCantTiposSolicitudes = Integer.parseInt(cantTiposSolicitudes);
                
                TipoSolicitud tipo  = null;
                for (int i = 1; i <= intCantTiposSolicitudes; i++) {
                    String strTipoSolicitud = props.getProperty("solicitudes"+i+".tipoSolicitud");
                     tipo = new TipoSolicitud(strTipoSolicitud);
                    tiposSolicitudes.add(tipo);
                }   
    }
    public void cargarEmpleados() throws Exception{
        File arch=new File("./data/empleados.properties");
		Properties props=new Properties();
		FileInputStream fis=new FileInputStream(arch);
		props.load(fis);
		String cantEmpleados = props.getProperty("cantidadEmpleados");
                int intCantEmpleados = Integer.parseInt(cantEmpleados);
                
                Empleado empleado = null;
                for (int i = 1; i <= intCantEmpleados; i++) {
                    String strId = props.getProperty("empleado"+i+".id");
                    int id = Integer.parseInt(strId);
                    String strNombre = props.getProperty("empleado"+i+".nombre");
                    String strTipoSolicitud = props.getProperty("empleado"+i+".tipoSolicitud");
                    empleado = new Empleado(id, strNombre, strTipoSolicitud);
                    empleados.add(empleado);
                }
    }
    public void cargarAreas() throws Exception{
        File arch=new File("./data/areas.properties");
		Properties props=new Properties();
		FileInputStream fis=new FileInputStream(arch);
		props.load(fis);
		String cantAreas = props.getProperty("cantidadAreas");
                int intcantareas = Integer.parseInt(cantAreas);
                
                Area area ;
                for (int i = 1; i <= intcantareas; i++) {
                    String strId = props.getProperty("Area"+i+".id");
                    int id = Integer.parseInt(strId);
                    String strNombre = props.getProperty("Area"+i+".nombre");
                    area = new Area(id, strNombre);
                    areas.add(area);
                }
    }
    public void cargarEquipos() throws Exception{
        File arch=new File("./data/equipos.properties");
		Properties props=new Properties();
		FileInputStream fis=new FileInputStream(arch);
		props.load(fis);
		String cantEquipos = props.getProperty("cantidadEquipos");
                int intcantEquipos = Integer.parseInt(cantEquipos);
                
                Equipo equipo = null;
                for (int i = 1; i <= intcantEquipos; i++) {
                    String strId = props.getProperty("equipo"+i+".id");
                    int id = Integer.parseInt(strId);
                    String strNombre = props.getProperty("equipo"+i+".nombre");
                    equipo = new Equipo(id, strNombre);
                    equipos.add(equipo);
                }
    }
    
    public void cargarUsuarios() throws Exception{
        File arch=new File("./data/usuarios.properties");
		Properties props=new Properties();
		FileInputStream fis=new FileInputStream(arch);
		props.load(fis);
		String cantUsuarios = props.getProperty("cantidadUsuarios");
                int intcantUsuarios = Integer.parseInt(cantUsuarios);
                
                Usuario usuario;
                for (int i = 1; i <= intcantUsuarios; i++) {
                    String strId = props.getProperty("usuario"+i+".id");
                    int id = Integer.parseInt(strId);
                    String strNombre = props.getProperty("usuario"+i+".nombre");
                    usuario = new Usuario(id, strNombre);
                    usuarios.add(usuario);
                    
                }
                
    }
    public void asociarEmpleadosArea(){
        Area area = null;
        for (int i = 0; i < areas.size(); i++) {
            area= areas.get(i);
            area.adicionarIdEmpleado(empleados.get(i));
            areas.set(i, area);
        }
    }
    public void asociarEquiposUsuarios(){
        Usuario usuario = null;
        for (int i = 0; i < usuarios.size(); i++) {
            usuario = usuarios.get(i);
            usuario.agregarEquipo(equipos.get(i));
            usuarios.set(i, usuario);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelArea;
    private javax.swing.JPanel PanelEmpleado;
    private javax.swing.JPanel PanelEquipo;
    private javax.swing.JPanel PanelMenu;
    private javax.swing.JPanel PanelSolicitud;
    private javax.swing.JPanel PanelTipoSolicitud;
    private javax.swing.JPanel PanelTitulo;
    private javax.swing.JPanel PanelUsuario;
    private javax.swing.JButton btnAddArea;
    private javax.swing.JButton btnAddEmpleado;
    private javax.swing.JButton btnAddEquipo;
    private javax.swing.JButton btnAgregarSolicitud;
    private javax.swing.JButton btnAgregarTipoSolicitud;
    private javax.swing.JButton btnAgregarUsuario;
    private javax.swing.JButton btnArea;
    private javax.swing.JButton btnEmpleado;
    private javax.swing.JButton btnEquipo;
    private javax.swing.JButton btnSolicitud;
    private javax.swing.JButton btnTipoSolicitud;
    private javax.swing.JButton btnUsuario;
    private javax.swing.JComboBox cmbArea;
    private javax.swing.JComboBox cmbTipo;
    private javax.swing.JComboBox cmbTipos;
    private javax.swing.JComboBox cmbUsuarioEquipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JList lstAreas;
    private javax.swing.JList lstEmpleados;
    private javax.swing.JList lstEquipos;
    private javax.swing.JList lstSlicitudes;
    private javax.swing.JList lstTipos;
    private javax.swing.JList lstUsuarios;
    private javax.swing.JList lstUsuariosEx;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtIdArea;
    private javax.swing.JTextField txtIdEmpleado;
    private javax.swing.JTextField txtIdEquipo;
    private javax.swing.JTextField txtIdUsuario;
    private javax.swing.JTextField txtNobreTipo;
    private javax.swing.JTextField txtNombreArea;
    private javax.swing.JTextField txtNombreEmpleado;
    private javax.swing.JTextField txtNombreEquipo;
    private javax.swing.JTextField txtNombreUsuario;
    // End of variables declaration//GEN-END:variables
}
